## Quiz 1 - Clasificación de Imagenes

¿Qué podría cambiar para hacer el código más limpio?

In [ ]:
import time

i = "path_image"

t = end_time - start # calcula el tiempo de ejecucion
c = classify(i) # obtiene la clase de la imagen
print("La duracion fue de {} segundos. La clase es {}" .format(t, c))

## Quiz 2 - Compra de criptomonedas

¿Cuál es el código más limpio y por qué?

In [ ]:
# Opcion A
crypto_limit_prices = {'BTC': 44000, 'ETH': 31000, 'BNB': 410}
for crypto_ticker, crypto_limit_price in buy_prices.items():
    if crypto_limit_price <= get_current_crypto_price(ticker):
        buy_crypto(ticker)
    else:
        watchlist_crypto(ticker)

# Opcion B
prices = {'BTC': 44000, 'ETH': 31000, 'BNB': 410}
for ticker, price in prices.items():
    if price <= current_price(ticker):
        buy(ticker)
    else:
        watchlist(ticker)

# Opcion C
limit_prices = {'BTC': 44000, 'ETH': 31000, 'BNB': 410}
for ticker, limit in limit_prices.items():
    if limit <= get_current_price(ticker):
        buy(ticker)
    else:
        watchlist(ticker)

## Quiz 3 - Renombrando Columnas

¿Puede refactorizar este código para hacerlo más limpio y modular?

In [25]:
import pandas as pd
import re 

df = pd.read_excel(r'Absenteeism_at_work.xls')
df.head()

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,239554,...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,239554,...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,239554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239554,...,0,1,2,1,0,1,90,172,30,2

In [29]:
def clean_column_name(column_name):
    '''Limpia y normaliza los nombres de las columnas'''

    column_name = column_name.strip().lower().replace(' ', '_')
    column_name = re.sub(r'[^a-z0-9_]', '', column_name)
    return column_name


absenteeism_df = df.rename(columns=clean_column_name)
print(absenteeism_df.head())

#region  No tocar funciona  
'''new_df = df.rename(columns={'ID': 'id',
                            'Reason for absence': 'reason_for_absence',
                            'Month of absence': 'month_of_absence',
                            'Day of the week': 'day_of_the_week',
                            'Seasons': 'seasons',
                            'Transportation expense': 'transportation_expense',
                            'Distance from Residence to Work': 'distance_from_residence_to_work',
                            'Service time': 'service_time',
                            'Age': 'age',
                            'Work load Average/day ': 'work_load_average/day_',
                            'Hit target': 'hit_target',
                            'Disciplinary failure': 'disciplinary_failure',
                            'Education': 'education',
                            'Son': 'son',
                            'Social drinker': 'social_drinker',
                            'Social smoker': 'social_smoker',
                            'Pet': 'pet',
                            'Weight': 'weight',
                            'Height': 'height',
                            'Body mass index': 'body_mass_index',
                            'Absenteeism time in hours': 'absenteeism_time_in_hours'
                            })
new_df.head()'''

   id  reason_for_absence  month_of_absence  day_of_the_week  seasons  \
0  11                  26                 7                3        1
1  36                   0                 7                3        1
2   3                  23                 7                4        1
3   7                   7                 7                5        1
4  11                  23                 7                5        1

   transportation_expense  distance_from_residence_to_work  service_time  age  \
0                     289                               36            13   33
1                     118                               13            18   50
2                     179                               51            18   38
3                     279                                5            14   39
4                     289                               36            13   33

   work_load_averageday  ...  disciplinary_failure  education  son  \
0                239554  ...                     0          1    2
1                239554  ...                     1          1    1
2                239554  ...                     0          1    0
3                239554  ...                     0          1    2
4                239554  ...                     0          1    2

   social_drinker  social_smoker  pet  weight  height  body_mass_index  \
0               1              0    1      90     172               30
1               1              0    0      98     178               31
2               1              0    0      89     170               31
3               1              1    0      68     168               24
4               1              0    1      90     172               30

   absenteeism_time_in_hours
0                          4
1                          0
2                          2
3                          4
4                          2

[5 rows x 21 columns]

"new_df = df.rename(columns={'ID': 'id',\n                            'Reason for absence': 'reason_for_absence',\n                            'Month of absence': 'month_of_absence',\n                            'Day of the week': 'day_of_the_week',\n                            'Seasons': 'seasons',\n                            'Transportation expense': 'transportation_expense',\n                            'Distance from Residence to Work': 'distance_from_residence_to_work',\n                            'Service time': 'service_time',\n                            'Age': 'age',\n                            'Work load Average/day ': 'work_load_average/day_',\n                            'Hit target': 'hit_target',\n                            'Disciplinary failure': 'disciplinary_failure',\n                            'Education': 'education',\n                            'Son': 'son',\n                            'Social drinker': 'social_drinker',\n                            'Social smoker': 'social_smoker',\n                            'Pet': 'pet',\n                            'Weight': 'weight',\n                            'Height': 'height',\n                            'Body mass index': 'body_mass_index',\n                            'Absenteeism time in hours': 'absenteeism_time_in_hours'\n                            })\nnew_df.head()"

Esta es otra forma un poco mejor que evita que se tengan problemas con letras o errores tipograficos.

In [ ]:
labels = list(df.columns)
labels[0] = labels[0].replace(' ', '_').lower()
labels[1] = labels[1].replace(' ', '_').lower()
labels[2] = labels[2].replace(' ', '_').lower()
labels[3] = labels[3].replace(' ', '_').lower()
labels[5] = labels[5].replace(' ', '_').lower()
labels[6] = labels[6].replace(' ', '_').lower()
labels[7] = labels[7].replace(' ', '_').lower()
labels[8] = labels[8].replace(' ', '_').lower()
labels[9] = labels[9].replace(' ', '_').lower()
labels[10] = labels[10].replace(' ', '_').lower()
labels[11] = labels[11].replace(' ', '_').lower()
labels[12] = labels[12].replace(' ', '_').lower()
labels[13] = labels[13].replace(' ', '_').lower()
labels[14] = labels[14].replace(' ', '_').lower()
labels[15] = labels[15].replace(' ', '_').lower()
labels[16] = labels[16].replace(' ', '_').lower()
labels[17] = labels[17].replace(' ', '_').lower()
labels[18] = labels[18].replace(' ', '_').lower()
labels[19] = labels[19].replace(' ', '_').lower()
labels[20] = labels[20].replace(' ', '_').lower()

df.columns = labels

df.head()